### ISSUE TITLE
Scroll + history back/forward glitch

### ISSUE THREAD

**Issue by mkv27** [ionic-team/stencil-site#127] opened 2018-02-10 18:16 UTC
Safari iOS 11.0+
1. Click <stencil-route-link>
2. Scroll
3. Back in history
4. Forward in history

Swipe:
https://www.dropbox.com/s/x61qdrzopwar5sj/swipe%20glitch.mov?dl=0
Arrows:
https://www.dropbox.com/s/8fszsgdwkut140l/arrows%20glitch.mov?dl=0

**Comment by rwaskiewicz** [comment] 2023-01-12 21:52
Thanks! I apologize it took so long on the team to respond to this. Since this issue was reported, our doc site has been updated/I'm no longer able to reproduce. I'm going to close this issue, but thank you for having reported it!

**Closed by rwaskiewicz** 2023-01-12 21:52 UTC
